2019-11-26 08:56:39,378 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 08:56:53,627 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 18:26:03,702 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 19:36:41,792 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 19:39:06,709 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 19:56:05,460 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:01:16,111 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:05:04,200 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:19:41,221 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:25:27,992 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:29:00,721 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-26 20:33:28,748 INFO: Logging Startup... [in /home/jace/Development/eecs-448/FinalProjectGOT/init.py:28]
2019-11-29 01:30:11,207 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:32:16,770 ERROR: Exception on /signup [POST] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 52, in signup
    if signup_not_empty(form):
NameError: name 'signup_not_empty' is not defined
2019-11-29 01:37:19,727 ERROR: Exception on /signup [POST] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 52, in signup
    if signup_not_empty(form):
NameError: name 'signup_not_empty' is not defined
2019-11-29 01:43:01,811 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:56:23,633 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:56:27,151 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:56:28,231 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:56:36,723 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:56:40,182 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:56:47,142 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:56:48,070 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:56:58,066 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:57:00,297 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#friends'. Did you mean 'account' instead?
2019-11-29 01:58:14,816 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:58:30,348 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 01:58:31,483 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#account'. Did you mean 'account' instead?
2019-11-29 01:58:45,752 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#account'. Did you mean 'account' instead?
2019-11-29 01:58:46,469 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#account'. Did you mean 'account' instead?
2019-11-29 01:58:53,562 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:04:29,514 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:04:31,315 ERROR: Exception on /home [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 67, in home
    return render_template('homepage.html')
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\homepage.html", line 16, in root
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 25, in root
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'account#account'. Did you mean 'account' instead?
2019-11-29 02:08:29,809 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:25:06,617 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:26:38,896 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:27:30,267 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:27:54,328 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:30:47,447 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:31:10,440 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:31:48,857 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:41:28,201 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:45:58,854 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:46:11,963 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:57:31,775 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:57:34,093 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 14, in root
    <div class= "mar-top">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 22, in block_page_content
    <label  class="col-sm-2 col-form-label">{{ form.first_name.label }}</label>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 36, in block_content
    {{ form.new_password(value=current_user.password) }}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'render_field' is undefined
2019-11-29 02:57:35,030 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 14, in root
    <div class= "mar-top">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 22, in block_page_content
    <label  class="col-sm-2 col-form-label">{{ form.first_name.label }}</label>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 36, in block_content
    {{ form.new_password(value=current_user.password) }}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'render_field' is undefined
2019-11-29 02:59:21,802 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 02:59:24,650 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 14, in root
    <div class= "mar-top">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 22, in block_page_content
    <label  class="col-sm-2 col-form-label">{{ form.first_name.label }}</label>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 36, in block_content
    {{ form.new_password(value=current_user.password) }}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2019-11-29 03:01:45,944 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:01:47,746 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 17, in root
    <h3>Update Account Information</h3><br><br>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 25, in block_page_content
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 39, in block_content
    {% endfor %}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 124, in macro
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtforms.widgets.core.HTMLString object' has no attribute 'flags'
2019-11-29 03:01:48,299 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 17, in root
    <h3>Update Account Information</h3><br><br>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 25, in block_page_content
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 39, in block_content
    {% endfor %}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 124, in macro
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtforms.widgets.core.HTMLString object' has no attribute 'flags'
2019-11-29 03:01:54,248 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 17, in root
    <h3>Update Account Information</h3><br><br>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 25, in block_page_content
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 39, in block_content
    {% endfor %}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 124, in macro
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtforms.widgets.core.HTMLString object' has no attribute 'flags'
2019-11-29 03:01:55,023 ERROR: Exception on /account [GET] [in c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\main.py", line 77, in account
    return render_template('account.html', form=form)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 17, in root
    <h3>Update Account Information</h3><br><br>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\base.html", line 46, in root
    <div class="flashed-message-box">
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 25, in block_page_content
    </div>
  File "C:\Users\17854\Documents\GitHub\FinalProjectGOT\templates\account.html", line 39, in block_content
    {% endfor %}<br>
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 124, in macro
    {% endif %}
  File "c:\users\17854\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtforms.widgets.core.HTMLString object' has no attribute 'flags'
2019-11-29 03:17:15,479 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:18:09,493 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:18:35,681 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:19:03,693 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:19:17,340 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:20:56,184 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:21:49,012 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:23:02,816 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:23:50,945 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:28:26,312 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:30:04,127 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:30:26,728 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:31:25,017 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:31:54,061 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:33:11,509 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:34:43,752 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:35:53,877 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:36:15,896 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:36:34,384 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:37:48,939 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:38:06,717 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:49:23,917 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 03:50:48,622 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 11:57:14,731 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 19:51:39,456 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
2019-11-29 20:29:55,159 INFO: Logging Startup... [in C:\Users\17854\Documents\GitHub\FinalProjectGOT\init.py:28]
